export const CIRCLE_CIRCUMFERENCE = 2 * Math.PI * 45;

export const DEFAULT_WORKOUT_CONFIG = {
  INTERVALS: 2,
  WORK_SECONDS: 30,
  REST_SECONDS: 180,
  WARMUP_SECONDS: 300,
  COOLDOWN_SECONDS: 300,
};

export const WARMUP_SECONDS = DEFAULT_WORKOUT_CONFIG.WARMUP_SECONDS;
export const REST_SECONDS = DEFAULT_WORKOUT_CONFIG.REST_SECONDS;
export const COOLDOWN_SECONDS = DEFAULT_WORKOUT_CONFIG.COOLDOWN_SECONDS;

export const SESSIONS_PER_WEEK = 3;

export const AUDIO_SETTINGS_KEY = "couchTo4x4.volume";
